
# /home/ros/Projects/SSP/gitHub/dice-dev/core/dakota/ply_parser_DakotaParser_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '64F473888874A8364AC542240F9B8ABC'
    
_lr_action_items = {'$end':([1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,],[-2,0,-10,-1,-7,-17,-20,-18,-14,-16,-15,-9,-12,-19,-11,-13,-6,-5,-4,-8,-3,]),'DQSCONST':([3,6,8,9,12,14,17,21,22,],[8,-17,-18,-14,8,8,-13,8,-14,]),'SCONST':([3,6,8,9,12,14,17,21,22,],[6,-17,-18,-14,6,6,-13,6,-14,]),'KEYWORD':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,15,16,17,18,19,20,21,22,],[3,-2,3,-10,-1,-7,-17,-20,-18,-14,-16,-15,-9,-12,-19,-11,-13,-6,-5,-4,-8,-3,]),'FCONST':([3,5,7,10,11,13,14,15,16,18,19,20,],[7,7,-20,-16,-15,-12,7,-19,-11,7,-16,-15,]),'EQUALS':([3,],[14,]),'ICONST':([3,5,7,10,11,13,14,15,16,18,19,20,],[15,15,-20,-16,-15,-12,15,-19,-11,15,-16,-15,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'float':([3,5,14,18,],[10,10,19,10,]),'reallist':([3,14,],[5,18,]),'key_value':([0,2,],[1,4,]),'block':([0,],[2,]),'stringlist':([3,14,],[12,21,]),'string_value':([3,12,14,21,],[9,17,22,17,]),'integer':([3,5,14,18,],[11,11,20,11,]),'number':([3,5,14,18,],[13,16,13,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> block","S'",1,None,None,None),
  ('block -> block key_value','block',2,'p_block','dakota_parser.py',216),
  ('block -> key_value','block',1,'p_block','dakota_parser.py',217),
  ('key_value -> KEYWORD EQUALS string_value','key_value',3,'p_key_value','dakota_parser.py',227),
  ('key_value -> KEYWORD EQUALS integer','key_value',3,'p_key_value','dakota_parser.py',228),
  ('key_value -> KEYWORD EQUALS float','key_value',3,'p_key_value','dakota_parser.py',229),
  ('key_value -> KEYWORD EQUALS reallist','key_value',3,'p_key_value','dakota_parser.py',230),
  ('key_value -> KEYWORD reallist','key_value',2,'p_key_value','dakota_parser.py',231),
  ('key_value -> KEYWORD EQUALS stringlist','key_value',3,'p_key_value','dakota_parser.py',232),
  ('key_value -> KEYWORD stringlist','key_value',2,'p_key_value','dakota_parser.py',233),
  ('key_value -> KEYWORD','key_value',1,'p_key_value','dakota_parser.py',234),
  ('reallist -> reallist number','reallist',2,'p_reallist','dakota_parser.py',245),
  ('reallist -> number','reallist',1,'p_reallist','dakota_parser.py',246),
  ('stringlist -> stringlist string_value','stringlist',2,'p_stringlist','dakota_parser.py',254),
  ('stringlist -> string_value','stringlist',1,'p_stringlist','dakota_parser.py',255),
  ('number -> integer','number',1,'p_number','dakota_parser.py',263),
  ('number -> float','number',1,'p_number','dakota_parser.py',264),
  ('string_value -> SCONST','string_value',1,'p_string_value','dakota_parser.py',268),
  ('string_value -> DQSCONST','string_value',1,'p_string_value','dakota_parser.py',269),
  ('integer -> ICONST','integer',1,'p_integer','dakota_parser.py',277),
  ('float -> FCONST','float',1,'p_float','dakota_parser.py',281),
  ('empty -> <empty>','empty',0,'p_empty','dakota_parser.py',286),
]
